apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: default
  labels:
    app: blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
      - name: blog-service
        image: aws_portfolio-blog-service:latest
        imagePullPolicy: Never  # 로컬 이미지 사용
        ports:
        - containerPort: 8102
          name: http
        envFrom:
        - configMapRef:
            name: blog-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8102
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8102
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: default
  labels:
    app: blog-service
spec:
  ports:
  - port: 8102
    targetPort: 8102
    name: http
  selector:
    app: blog-service
  type: ClusterIP 